
import { toLocalISOString } from '../utils/date';

export const generatedCategories = [
  {
    "id": 1,
    "name": "有機藜麥燉飯",
    "description": "有機藜麥燉飯",
    "sortOrder": 1,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 2,
    "name": "有機藜麥白飯(燴飯)",
    "description": "有機藜麥白飯(燴飯)",
    "sortOrder": 2,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 3,
    "name": "有機藜麥白飯(醬汁飯)",
    "description": "有機藜麥白飯(醬汁飯)",
    "sortOrder": 3,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 4,
    "name": "有機藜麥白飯(丼飯)",
    "description": "有機藜麥白飯(丼飯)",
    "sortOrder": 4,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 5,
    "name": "鍋炒烏龍麵",
    "description": "鍋炒烏龍麵",
    "sortOrder": 5,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 6,
    "name": "虎皮蛋捲餅",
    "description": "虎皮蛋捲餅",
    "sortOrder": 6,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 7,
    "name": "總匯吐司蛋",
    "description": "總匯吐司蛋",
    "sortOrder": 7,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 8,
    "name": "蘿蔔糕特餐",
    "description": "蘿蔔糕特餐",
    "sortOrder": 8,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 9,
    "name": "有機高麗菜綜合沙拉",
    "description": "有機高麗菜綜合沙拉",
    "sortOrder": 9,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 10,
    "name": "果醬吐司(2片)",
    "description": "果醬吐司(2片)",
    "sortOrder": 10,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 11,
    "name": "點心",
    "description": "點心",
    "sortOrder": 11,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 12,
    "name": "茶類/奶茶",
    "description": "茶類/奶茶",
    "sortOrder": 12,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 13,
    "name": "咖啡/熱飲",
    "description": "咖啡/熱飲",
    "sortOrder": 13,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 14,
    "name": "點心代號說明",
    "description": "點心代號說明",
    "sortOrder": 14,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  },
  {
    "id": 15,
    "name": "有機藜麥義大利麵",
    "description": "有機藜麥義大利麵",
    "sortOrder": 15,
    "isActive": true,
    "icon": "rice",
    "color": "#ef4444"
  }
];
export const generatedProducts = [
  {
    "categoryId": 1,
    "name": "松子粒(素)",
    "description": "",
    "price": 125,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 1
  },
  {
    "categoryId": 1,
    "name": "菇菇(素)",
    "description": "",
    "price": 145,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 2
  },
  {
    "categoryId": 1,
    "name": "100%黑豬肉",
    "description": "",
    "price": 145,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 3
  },
  {
    "categoryId": 1,
    "name": "100%菲瑞牛",
    "description": "",
    "price": 145,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 4
  },
  {
    "categoryId": 1,
    "name": "花蛤",
    "description": "",
    "price": 150,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 5
  },
  {
    "categoryId": 1,
    "name": "100%炸雞條",
    "description": "",
    "price": 150,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 6
  },
  {
    "categoryId": 1,
    "name": "100%醬燒雞腿",
    "description": "",
    "price": 160,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 7
  },
  {
    "categoryId": 1,
    "name": "100%舒肥雞胸",
    "description": "",
    "price": 160,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 8
  },
  {
    "categoryId": 2,
    "name": "黑豬醬",
    "description": "",
    "price": 90,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 9
  },
  {
    "categoryId": 2,
    "name": "菇菇(蛋素)",
    "description": "",
    "price": 90,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 10
  },
  {
    "categoryId": 3,
    "name": "杏鮑菇菇(素)",
    "description": "",
    "price": 90,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 11
  },
  {
    "categoryId": 3,
    "name": "100%梅花豬",
    "description": "",
    "price": 90,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 12
  },
  {
    "categoryId": 3,
    "name": "100%炸雞條",
    "description": "",
    "price": 95,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 13
  },
  {
    "categoryId": 3,
    "name": "100%菲瑞牛飯",
    "description": "",
    "price": 105,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 14
  },
  {
    "categoryId": 3,
    "name": "100%醬燒雞腿",
    "description": "",
    "price": 135,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 15
  },
  {
    "categoryId": 3,
    "name": "100%舒肥雞胸",
    "description": "",
    "price": 150,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 16
  },
  {
    "categoryId": 4,
    "name": "洋蔥醬燒豬",
    "description": "",
    "price": 115,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 17
  },
  {
    "categoryId": 4,
    "name": "洋蔥醬燒牛肋條",
    "description": "",
    "price": 135,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 18
  },
  {
    "categoryId": 5,
    "name": "100%黑胡椒",
    "description": "",
    "price": 90,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 19
  },
  {
    "categoryId": 5,
    "name": "杏鮑菇菇(素)",
    "description": "",
    "price": 100,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 20
  },
  {
    "categoryId": 5,
    "name": "100%黑豬肉",
    "description": "",
    "price": 100,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 21
  },
  {
    "categoryId": 5,
    "name": "黑豬肉黑胡椒",
    "description": "",
    "price": 110,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 22
  },
  {
    "categoryId": 5,
    "name": "杏鮑菇黑胡椒醬",
    "description": "",
    "price": 110,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 23
  },
  {
    "categoryId": 6,
    "name": "原味(素)",
    "description": "",
    "price": 50,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 24
  },
  {
    "categoryId": 6,
    "name": "玉米(素)",
    "description": "",
    "price": 60,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 25
  },
  {
    "categoryId": 6,
    "name": "薯餅(素)",
    "description": "",
    "price": 70,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 26
  },
  {
    "categoryId": 6,
    "name": "杏鮑菇(素)",
    "description": "",
    "price": 75,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 27
  },
  {
    "categoryId": 6,
    "name": "梅花豬",
    "description": "",
    "price": 75,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 28
  },
  {
    "categoryId": 6,
    "name": "菲瑞牛",
    "description": "",
    "price": 80,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 29
  },
  {
    "categoryId": 6,
    "name": "鮪魚玉米大板燒",
    "description": "",
    "price": 80,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 30
  },
  {
    "categoryId": 7,
    "name": "玉米(素)",
    "description": "",
    "price": 55,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 31
  },
  {
    "categoryId": 7,
    "name": "薯餅(素)",
    "description": "",
    "price": 65,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 32
  },
  {
    "categoryId": 7,
    "name": "鮪魚玉米",
    "description": "",
    "price": 70,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 33
  },
  {
    "categoryId": 7,
    "name": "杏鮑菇(素)",
    "description": "",
    "price": 75,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 34
  },
  {
    "categoryId": 7,
    "name": "梅花豬",
    "description": "",
    "price": 75,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 35
  },
  {
    "categoryId": 7,
    "name": "菲瑞牛",
    "description": "",
    "price": 80,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 36
  },
  {
    "categoryId": 7,
    "name": "炸雞條",
    "description": "",
    "price": 85,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 37
  },
  {
    "categoryId": 7,
    "name": "舒肥雞胸",
    "description": "",
    "price": 110,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 38
  },
  {
    "categoryId": 8,
    "name": "蘿蔔糕X2+煎蛋",
    "description": "",
    "price": 50,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 39
  },
  {
    "categoryId": 8,
    "name": "梅花豬蘿蔔糕(蛋)",
    "description": "",
    "price": 85,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 40
  },
  {
    "categoryId": 8,
    "name": "菲瑞牛蘿蔔糕(蛋)",
    "description": "",
    "price": 90,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 41
  },
  {
    "categoryId": 8,
    "name": "醬燒雞腿蘿蔔糕(蛋)",
    "description": "",
    "price": 115,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 42
  },
  {
    "categoryId": 8,
    "name": "舒肥雞胸蘿蔔糕(蛋)",
    "description": "",
    "price": 120,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 43
  },
  {
    "categoryId": 9,
    "name": "菲瑞牛(蛋)",
    "description": "",
    "price": 160,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 44
  },
  {
    "categoryId": 9,
    "name": "醬燒雞腿(蛋)",
    "description": "",
    "price": 165,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 45
  },
  {
    "categoryId": 9,
    "name": "舒肥雞胸(蛋)",
    "description": "",
    "price": 170,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 46
  },
  {
    "categoryId": 10,
    "name": "吉比花生醬(蛋奶素)",
    "description": "",
    "price": 45,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 47
  },
  {
    "categoryId": 10,
    "name": "綜合堅果醬(蛋奶素)",
    "description": "",
    "price": 50,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 48
  },
  {
    "categoryId": 11,
    "name": "荷包蛋",
    "description": "",
    "price": 15,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 49
  },
  {
    "categoryId": 11,
    "name": "薯餅一片(素)",
    "description": "",
    "price": 25,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 50
  },
  {
    "categoryId": 11,
    "name": "港式蘿蔔糕(葷)",
    "description": "",
    "price": 45,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 51
  },
  {
    "categoryId": 11,
    "name": "地瓜(素)",
    "description": "",
    "price": 45,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 52
  },
  {
    "categoryId": 11,
    "name": "有機高麗菜沙拉",
    "description": "",
    "price": 50,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 53
  },
  {
    "categoryId": 11,
    "name": "花蛤湯",
    "description": "",
    "price": 50,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 54
  },
  {
    "categoryId": 11,
    "name": "脆薯條",
    "description": "",
    "price": 50,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 55
  },
  {
    "categoryId": 11,
    "name": "100%炸雞條",
    "description": "",
    "price": 60,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 56
  },
  {
    "categoryId": 12,
    "name": "有機蔗糖紅茶",
    "description": "",
    "price": 30,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 57
  },
  {
    "categoryId": 12,
    "name": "三種成份奶茶",
    "description": "",
    "price": 50,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 58
  },
  {
    "categoryId": 12,
    "name": "豆漿(非基改黃豆)",
    "description": "",
    "price": 30,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 59
  },
  {
    "categoryId": 12,
    "name": "豆漿紅茶(糖)",
    "description": "",
    "price": 30,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 60
  },
  {
    "categoryId": 13,
    "name": "有機美式咖啡",
    "description": "",
    "price": 60,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 61
  },
  {
    "categoryId": 13,
    "name": "有機拿鐵(100%奶粉)",
    "description": "",
    "price": 70,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 62
  },
  {
    "categoryId": 13,
    "name": "100%牛奶",
    "description": "",
    "price": 50,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 63
  },
  {
    "categoryId": 13,
    "name": "生機洛神乾果粒",
    "description": "",
    "price": 50,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 64
  },
  {
    "categoryId": 14,
    "name": "A",
    "description": "",
    "price": 0,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 65
  },
  {
    "categoryId": 14,
    "name": "B",
    "description": "",
    "price": 0,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 66
  },
  {
    "categoryId": 14,
    "name": "C",
    "description": "",
    "price": 0,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 67
  },
  {
    "categoryId": 14,
    "name": "D",
    "description": "",
    "price": 0,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 68
  },
  {
    "categoryId": 14,
    "name": "E",
    "description": "",
    "price": 0,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 69
  },
  {
    "categoryId": 14,
    "name": "F",
    "description": "",
    "price": 0,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 70
  },
  {
    "categoryId": 14,
    "name": "G",
    "description": "",
    "price": 0,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 71
  },
  {
    "categoryId": 15,
    "name": "松子粒(素)",
    "description": "",
    "price": 125,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 72
  },
  {
    "categoryId": 15,
    "name": "菇菇(素)",
    "description": "",
    "price": 145,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 73
  },
  {
    "categoryId": 15,
    "name": "100%黑豬肉",
    "description": "",
    "price": 145,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 74
  },
  {
    "categoryId": 15,
    "name": "100%菲瑞牛",
    "description": "",
    "price": 145,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 75
  },
  {
    "categoryId": 15,
    "name": "花蛤",
    "description": "",
    "price": 150,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 76
  },
  {
    "categoryId": 15,
    "name": "100%炸雞條",
    "description": "",
    "price": 150,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 77
  },
  {
    "categoryId": 15,
    "name": "100%醬燒雞腿",
    "description": "",
    "price": 160,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 78
  },
  {
    "categoryId": 15,
    "name": "100%舒肥雞胸",
    "description": "",
    "price": 160,
    "imageUrl": "",
    "isActive": true,
    "modifierGroupIds": [],
    "trackInventory": false,
    "sortOrder": 79
  }
];
